#!/bin/bash

cd
echo ""
echo "Сlick on allow to proceed"
termux-setup-storage & sleep 4 &>/dev/null
while true; do
if [ -e storage ]; then
rm -rf /sdcard/termux-box
break
else
echo "If you denied permission, change it manually in termux app settings now"
fi
sleep 1
done
mkdir -p /sdcard/termux-box
pkg clean
pkg update -y
pkg upgrade -y
sleep 2
echo ""
echo "Installing packages"
pkg install x11-repo pulseaudio xwayland wget proot tsu root-repo -y &>/dev/null

rm -rf $HOME/termux-box
mkdir -p $HOME/termux-box
cd $HOME/termux-box
wget https://github.com/olegos2/termux-box/raw/main/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
mv termux-x11-1.02.07-0-all.deb /sdcard/Download

echo ""
echo "Downloading preconfigured Rootfs..."
cd $HOME/termux-box
wget -q --show-progress https://github.com/olegos2/termux-box/releases/download/0.0.1-alpha/rootfs.tar.xz

echo ""
echo "Unzipping Rootfs"
tar -xf rootfs.tar.xz
mv rootfs.tar.xz /sdcard/Download

cd $HOME/termux-box/ubuntu-fs/opt
wget https://github.com/olegos2/termux-box/raw/main/scripts.tar.gz &>/dev/null
tar -xf scripts.tar.gz
mv scripts.tar.gz /sdcard

cd $HOME/termux-box/
wget -N https://github.com/olegos2/termux-box/raw/main/termux-box &>/dev/null
chmod +x termux-box
mv termux-box $PREFIX/bin/
wget -N https://github.com/olegos2/termux-box/raw/main/start-proot.sh &>/dev/null
wget -N https://github.com/olegos2/termux-box/raw/main/start-chroot.sh &>/dev/null
chmod +x start-proot.sh
chmod +x start-chroot.sh

echo "Installing patch"

cd $HOME/termux-box/ubuntu-fs
wget -q --show-progress https://github.com/olegos2/termux-box/releases/download/0.0.1-alpha/patch.tar.xz
tar -xf patch.tar.xz
rm -rf patch.tar.xz
cd
rm -rf "$0"
. $PREFIX/bin/termux-box
